dataprep<-function(data){
  data %>% 
    select(CASEID,
      year,V012,
      V190,
      V150,
      V025,
      V103,
      V136,
      V131,
      V024,
      V155,
      V001,
      V005,
      V022,
      HV115,
      S108N,
      SREGION,
      S621,
      S704N,
      S802,
      S815AA,
      S815AB,
      S815AC,
      S815AD,
      S815AE,
      S815AX,
      S815AZ,
      S816AA,
      S816AB,
      S816AC,
      S816AD,
      S816AE,
      S816AF,
      S816AG,
      S816AH,
      S816AI,
      S816AJ,
      S816AK,
      S816AL,
      S816AW,
      S816AZ,
      #S413,
      S411G,
      S411H,
      M2A,
      M2B,
      M2C,
      M2D,
      M2E,
      M2F,
      M2G,
      M2H,
      M2I,
      M2J,
      M2K,
      M2L,
      M2M,
      M2N,
      M10,
      M13,
      M14,
      M57E,
      M57F,
      M57G,
      M57H,
      M57I,
      M57J,
      M57K,
      M57L,
      M57M,
      M57N,
      M57O,
      M57P,
      M57Q,
      M57R,
      M57S,
      M57T,
      M57U,
      M57V,
      M57X,
      D118Y,
      V763A,
      V763B,
      V763C,
      V774A,
      V774B,
      V774C,
      V201,
      V208,
      V211,
      SH11A,
      SH11B,
      SH11C,
      SH11D,
      SH11E,
      SH11Y,
      SH11Z,
      V209,
      V213,
      V214,
    ) %>% 
    
    mutate(
      V005 = V005/1000000,
      
      EDAD_MADRE = ifelse(V012<25,"15-24a",
                          ifelse(V012>=25&V012<30,"25-30a",
                                 ifelse(V012>=30&V012<35,"30-35a",
                                        ifelse(V012>=35,"35 a mas",NA)))),
      
      WEALTH_INDEX = factor(V190, levels = c(1:5), labels = c("POOREST","POOR","MIDDLE","RICH","RICHEST")),
      
      RELATIONSHIP_HOUSEHOLD_HEAD = ifelse(V150==1,"HEAD", 
                            ifelse(V150==2, "WIFE", 
                                   ifelse(V150==3, "DAUGTHER/SON", 
                                          ifelse(V150>=4, "OTHER", NA)))),
      
      TYPE_PLACE_RESIDENCE = ifelse(V025==1,"URBAN","RURAL"),
      
      ETHNICITY = factor(V131, levels = c(1:12), labels = c("QUECHUA","AYMARA","ASHANINKA","AWAJUN",
                                                            "SHIPIBO","SHAWI","MATSIGENKA","ACHUAR",
                                                            "OTHER","CASTELLANO","PORTUGUES","OTHER_FOREIGN_LANGUAGE")),
      
      DEPARTAMEN = factor(V024, levels = c(1:25), labels = c("AMAZONAS","ANCASH","APURIMAC","AREQUIPA","AYACUCHO",
                                                             "CAJAMARCA","CALLAO","CUSCO","HUANCAVELICA","HUANUCO",
                                                             "ICA","JUNIN","LA LIBERTAD","LAMBAYEQUE","LIMA",
                                                             "LORETO","MADRE DE DIOS","MOQUEGUA","PASCO","PIURA",
                                                             "PUNO","SAN MARTIN","TACNA","TUMBES","UCAYALI")),
      
      LITERACY = factor(V155, levels = c(0:4), labels = c("CANNOT_READ_AT_ALL","ABLE_TO_READ_ONLY_PARTS_OF_SENTENCE",
      "ABLE_TO_READ_WHOLE_SENTENCE","NO_CARD_WITH_REQUIRED_LANGUAGE","BLIND/VISUALLY_IMPAIRED")),
      
      CURRENT_MARITAL_STATUS = ifelse(HV115==0,"SINGLE", 
                            ifelse(HV115>=1&HV115<=2,"MARRIED/LIVING_TOGETHER", 
                                   ifelse(HV115>=3,"WIDOWED/DIVORCED/SEPARATED",NA))),
      
      EDU_LEVEL = as.factor(factor(S108N, levels = c(0,1,2,3,4,5,9), labels = c("NONE/PRESCHOOL","PRIMARY","SECONDARY","NON-UNIVERSITY_HIGHER","UNIVERSITY_HIGHER","POSTGRADUATE","MISSING"))),
      
      NATURAL_REGION = factor(SREGION, levels = c(1:4), labels = c("LIMA_METROPOLITAN","REST_OF_COAST","HIGHLAND","JUNGLE")),
      
      PARTNER_APPROVE_DISAPPROVE_FAMILY_PLANNING = factor(S621, levels = c(1,2,8), labels = c("APPROVE","DISAPPROVE","DONT_KNOW")),
      
      PARTNER_EDU_LEVEL = factor(S704N, levels = c(0,1,2,3,4,5,8), labels = c("NONE/PRESCHOOL","PRIMARY","SECONDARY","NON-UNIVERSITY_HIGHER","UNIVERSITY_HIGHER","POSTGRADUATE","DONT_KONW")),
      
      CAN_SOMETHING_BE_DONE_PREVENT_AIDS = factor(S802, levels = c(0,1,8), labels = c("NO","YES","DONT_KNOW")),
      
      
      KNOW_ETS = (S815AA+S815AB+S815AC+S815AD+S815AE+S815AX+S815AZ) , KNOW_ETS=case_when(KNOW_ETS==0~"Ninguna",
                                                                                      KNOW_ETS==1~"Almenos1",
                                                                                      KNOW_ETS>=2~"Masde1"),
      
      KNOW_SYMPTON_ETS = (S816AA+S816AB+S816AC+S816AD+S816AE+S816AF+S816AG+S816AH+S816AI+S816AJ+S816AK+S816AL+S816AW+S816AZ) , KNOW_ETS=case_when(KNOW_ETS==0~"NO",
                                                                                         KNOW_ETS>=1~"YES"),
      
      CHECKUP_RULE_OUT_SYPHILIS = factor(S411G, levels = c(0,1,8), labels = c("NO","YES","DONT_KNOW")),
      
      CHECKUP_RULE_OUT_HIV_AIDS = factor(S411G, levels = c(0,1,8), labels = c("NO","YES","DONT_KNOW")),

      M10 = factor(M10, levels = c(1,2,3), labels = c("ENTONCES","ESPERAR_MAS","NO_QUERIA_MAS")),

      PHYSICAL_VIOLENCE_PREGNANCY_NOBODY= factor(D118Y, levels = c(0,1), labels = c("NO","YES")),
      
      DIAGNOSTED_STD_LAST_12_MONTHS = factor(S411G, levels = c(0,1,8), labels = c("NO","YES","DONT_KNOW")),
      
      GENITAL_SORES_ULCERS_LAST_12_MONTHS = factor(V763B, levels = c(0,1,8), labels = c("NO","YES","DONT_KNOW")),
      
      #KNOW_TRANSMIT_MOTHER_TO_DS = (V774A+V774B+V774C) , KNOW_TRANSMIT_MOTHER_TO_DS=case_when(KNOW_ETS==0~"NO",KNOW_ETS>=1~"YES"),
      
      MIEMBROS_HOGAR = ifelse(V136<5,"1-4",
                          ifelse(V136>=5&V136<7,"5-6",
                              ifelse(V012>=7,"7 a mas",NA))),
  
      ETNIA_MADRE = ifelse(V131==10,"castellano",
                           ifelse(V131==1, "quechua",
                                  ifelse(V131==2, "aimara",
                                         ifelse(V131>=3&V131<=9, "amazonía",
                                                ifelse(V131>=11,"extranjero",NA))))),
      
      
      #EDAD_HIJOS = ifelse(HC1<=12, "menor igual a 12 meses", "mayor de 12 meses"),
      
      
    )
}
