---
title: "Untitled"
author: "jose"
date: '2022-08-19'
output:
  html_document: default
  pdf_document: default
---

```{r}
library(tidyverse)
library(survey)
library(gtsummary)
library(ggsci)
library(DT)
library(patchwork)
library(cowplot)
library(sf)
library(rcartocolor)
departamento <- sf::read_sf("data/Regiones/DEPARTAMENTOS.shp")
```


```{r}
df_gestantes<- read.csv("./data/datatest.csv") 

```

# Grafico 1

## HIV

```{r}
df<-
  df_gestantes %>% 
  mutate(
    CHECKUP_RULE_OUT_HIV2 = ifelse(is.na(CHECKUP_RULE_OUT_HIV),"Missing",
                   ifelse(CHECKUP_RULE_OUT_HIV == 1,"Yes",
                          ifelse(CHECKUP_RULE_OUT_HIV == 0 | CHECKUP_RULE_OUT_HIV == 8 , "No",CHECKUP_RULE_OUT_HIV))),
    
    CHECKUP_RULE_OUT_HIV2 = as.factor(CHECKUP_RULE_OUT_HIV2)
  ) %>% 
  group_by(year) %>% 
  nest() %>% 
  mutate(
    datasvy = map(.x = data,
                  .f = ~svydesign(id =~ V001, strata =~ V022, weights=~V005, data=.x))
  )
options(survey.lonely.psu="remove")
```


```{r}
hiv_df<-
  df %>% 
  mutate(
    
    vih = map(.x = datasvy,
              .f = ~svymean(~as.factor(CHECKUP_RULE_OUT_HIV2), design = .x, na.rm = T)),
    
    vihprop = map(.x = vih,
                  .f = ~as.numeric(.x)),
    
    vihci = map(.x= vih,
                .f = ~confint(.x) %>% 
                  as.data.frame() %>%
                  rownames_to_column("var"))
    
  ) %>% 
  
  unnest(c(vihci,vihprop)) %>% 
  
  mutate(
    var = case_when(var == "as.factor(CHECKUP_RULE_OUT_HIV2)Missing" ~ "Missing",
                    var == "as.factor(CHECKUP_RULE_OUT_HIV2)YES" ~ "Yes",
                    var == "as.factor(CHECKUP_RULE_OUT_HIV2)NO" ~ "No")
  )  



hiv_df %>% 
  select(year,var,vihprop,`2.5 %`,`97.5 %`) %>% 
  mutate(
    across(.cols = vihprop:`97.5 %`, .fns = ~round(.*100,1))
  ) %>% 
  DT::datatable()
```

### grafico HIV 1
```{r}
hiv<-
  ggplot(hiv_df %>%
           filter(var != "Missing"), aes(x = year, y = vihprop*100, ymin = `2.5 %`*100, ymax = `97.5 %`*100, group = var)) + 
    geom_line(size = 1.2, aes(col = var))+
  geom_ribbon(aes(fill = var), alpha = 0.1)+
  #geom_errorbar(aes(color=var), width = 0.2, alpha = 0.35) +
  xlab("Years") +
    ylab("Prop. %")+
  scale_x_continuous(expand = c(0, 0), breaks = c(2010:2021), limits = c(2010,2021.1))+
  ggsci::scale_fill_futurama(alpha = 0.8)+
  ggsci::scale_color_futurama(alpha = 0.8)+

  
  theme_bw()+
  
  theme(
    axis.title = element_text(face ="bold", size = 11),
    legend.text = element_text(size = 8, face = "bold"),
    axis.text = element_text(face = "bold", family = "Arial"),
    axis.text.x = element_text( size = 9),
    legend.position = "top",
    legend.title = element_blank(),
    axis.line = element_line(colour = "black", size = 1),
    panel.background = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(face = "bold"),
    panel.grid = element_blank()
  )

#ggsave("grafico1a.png", dpi = 300, width = 10)
```

### grafico HIV 2
```{r}
bar_hiv<-
  ggplot(hiv_df, aes(x = year, y = vihprop*100, group = var)) + 
  geom_col(size = 1.2, aes(fill = var))+
  ggsci::scale_fill_futurama(alpha = 0.8)+
  
  xlab("Years") +
  scale_x_continuous(expand = c(0, 0), breaks = c(2010:2021), limits = c(2009.5,2021.6))+
  ylab("Prop. %")+
  
  theme_bw()+
  
  theme(
    axis.title = element_text(face ="bold", size = 11),
    legend.text = element_text(face = "bold", size = 12),
    axis.text = element_text(face = "bold"),
    legend.position = "top",
    legend.title = element_blank(),
    strip.text = element_text(face = "bold"),
    panel.grid = element_blank()
  )

#ggsave("grafico1b.png", dpi = 300, width = 8)
```


## WEALTH INDEX


```{r}
df_gestantes2<-
  df_gestantes %>% 
    
  mutate(
    CHECKUP_RULE_OUT_HIV = ifelse(is.na(CHECKUP_RULE_OUT_HIV),"NO",CHECKUP_RULE_OUT_HIV)
  )
```


```{r}
###############
df<-
  df_gestantes2 %>% 
  mutate(
    CHECKUP_RULE_OUT_HIV2 = ifelse(is.na(CHECKUP_RULE_OUT_HIV),"Missing",
                   ifelse(CHECKUP_RULE_OUT_HIV == 1,"Yes",
                          ifelse(CHECKUP_RULE_OUT_HIV == 0 | CHECKUP_RULE_OUT_HIV == 8 , "No",CHECKUP_RULE_OUT_HIV))),
    
    CHECKUP_RULE_OUT_HIV2 = as.factor(CHECKUP_RULE_OUT_HIV2)
  ) %>% 
  group_by(year) %>% 
  nest() %>% 
  mutate(
    datasvy = map(.x = data,
                  .f = ~svydesign(id =~ V001, strata =~ V022, weights=~V005, data=.x))
  )
options(survey.lonely.psu="remove")

###############

wi_df<-
  df %>% 
  group_by(year) %>% 
  mutate(
    vih = map(.x = datasvy,
              .f = ~svyby(~as.factor(CHECKUP_RULE_OUT_HIV), by = ~WEALTH_INDEX, design = .x, FUN =svyciprop, vartype=c('se','ci')) %>% 
                as.data.frame())
  ) %>% 
  unnest(vih) 
options(survey.lonely.psu="remove")


wi_df %>% 
  mutate(
    across(`as.factor(CHECKUP_RULE_OUT_HIV)`:ci_u,.fns = ~round(.,3)*100)) %>% 
  
    DT::datatable()
```

## EDUCATION
```{r}


edu_df<-
  df %>% 
  dplyr::group_by(year) %>% 
  mutate(
    vih = map(.x = datasvy,
              .f = ~svyby(~as.factor(CHECKUP_RULE_OUT_HIV), by = ~EDU_LEVEL, design = .x, FUN =svyciprop, vartype=c('se','ci'), na.rm.by = T) %>% 
                as.data.frame())
  ) %>% 
  unnest(vih) 
  
 edu_df %>% 
  mutate(
    across(`as.factor(CHECKUP_RULE_OUT_HIV)`:ci_u,.fns = ~round(.,3)*100)) %>% 
  
    DT::datatable() 
  
```


```{r}
 
hiv_wi<-
  ggplot()+
  
  geom_line(data = wi_df, aes(x = year, y = `as.factor(CHECKUP_RULE_OUT_HIV)`*100,col = WEALTH_INDEX, ymin = ci_l*100, ymax = ci_u*100),
            size = 0.8, alpha = 0.4)+
  
  # geom_line(data = hiv_df %>% filter(var == "Yes"),
  #           aes(x = year, y = vihprop*100, ymin = `2.5 %`*100, ymax = `97.5 %`*100), col = "#70284a", size = 1.2)+
  # geom_ribbon(data = hiv_df %>% filter(var == "Yes"),
  #             aes(x = year, y = vihprop*100, ymin = `2.5 %`*100, ymax = `97.5 %`*100), fill = "#70284a",alpha = 0.1)+


  ggsci::scale_color_lancet()+
  
  
  xlab("Years") +
  scale_x_continuous(expand = c(0, 0), breaks = c(2010:2021), limits = c(2010,2021.2))+
  ylab("Prop. %")+
  theme_bw()+
  theme(
    axis.title = element_text(face ="bold", size = 11),
    legend.text = element_text(size = 8, face = "bold"),
    axis.text = element_text(face = "bold", family = "Arial"),
    axis.text.x = element_text( size = 9),
    legend.position = "top",
    legend.title = element_blank(),
    axis.line = element_line(colour = "black", size = 1),
    panel.background = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(face = "bold"),
    panel.grid = element_blank()
  )

#ggsave("test.png",dpi = 300, width = 8, height = 6)



```



```{r}
hiv_edu<-
  ggplot()+
  
  geom_line(data = edu_df, aes(x = year, y = `as.factor(CHECKUP_RULE_OUT_HIV)`*100,col = EDU_LEVEL, ymin = ci_l*100, ymax = ci_u*100),
            size = 0.8, alpha = 0.4)+
  
  # geom_line(data = hiv_df %>% filter(var == "Yes"),
  #           aes(x = year, y = vihprop*100, ymin = `2.5 %`*100, ymax = `97.5 %`*100), col = "#70284a", size = 1.2)+
  # geom_ribbon(data = hiv_df %>% filter(var == "Yes"),
  #             aes(x = year, y = vihprop*100, ymin = `2.5 %`*100, ymax = `97.5 %`*100), fill = "#70284a",alpha = 0.1)+


  ggsci::scale_color_lancet()+
  #scale_color_manual(values = c("#675353","#575573","#BFA5A5","#355F5F","#005FAA"))+
  
  xlab("Years") +
  scale_x_continuous(expand = c(0, 0), breaks = c(2010:2021), limits = c(2010,2021.2))+
  ylab("Prop. %")+
  theme_bw()+
  theme(
    axis.title = element_text(face ="bold", size = 11),
    axis.title.y = element_blank(),
    legend.text = element_text(size = 8, face = "bold"),
    axis.text = element_text(face = "bold", family = "Arial"),
    axis.text.x = element_text( size = 9),
    legend.position = "top",
    legend.title = element_blank(),
    axis.line = element_line(colour = "black", size = 1),
    panel.background = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(face = "bold"),
    panel.grid = element_blank()
  )

#ggsave("test2.png",dpi = 300, width = 10, height = 8)

```


```{r}
plot_grid(hiv_wi,hiv_edu,labels = c("a","b"))

ggsave("grafico2.png", dpi = 300, width = 12, height = 5)

```

## SIFILIS

```{r}
df<-
  df_gestantes %>% 
  mutate(
    CHECKUP_RULE_OUT_SYPHILIS2 = ifelse(is.na(CHECKUP_RULE_OUT_SYPHILIS),"Missing",
                   ifelse(CHECKUP_RULE_OUT_SYPHILIS == 1,"Yes",
                          ifelse(CHECKUP_RULE_OUT_SYPHILIS == 0 | CHECKUP_RULE_OUT_SYPHILIS == 8 , "No",CHECKUP_RULE_OUT_SYPHILIS))),
    CHECKUP_RULE_OUT_SYPHILIS2 = as.factor(CHECKUP_RULE_OUT_SYPHILIS2)
  ) %>% 
  group_by(year) %>% 
  nest() %>% 
  mutate(
    datasvy = map(.x = data,
                  .f = ~svydesign(id =~ V001, strata =~ V022, weights=~V005, data=.x))
  )
options(survey.lonely.psu="remove")
```


```{r}
df2<-
  df %>% 
  mutate(
    
    vih = map(.x = datasvy,
              .f = ~svymean(~as.factor(CHECKUP_RULE_OUT_SYPHILIS2), design = .x, na.rm = T)),
    
    vihprop = map(.x = vih,
                  .f = ~as.numeric(.x)),
    
    vihci = map(.x= vih,
                .f = ~confint(.x) %>% 
                  as.data.frame() %>%
                  rownames_to_column("var"))
    
  ) %>% 
  
  unnest(c(vihci,vihprop)) %>% 
  
  mutate(
    var = case_when(var == "as.factor(CHECKUP_RULE_OUT_SYPHILIS2)Missing" ~ "Missing",
                    var == "as.factor(CHECKUP_RULE_OUT_SYPHILIS2)YES" ~ "Yes",
                    var == "as.factor(CHECKUP_RULE_OUT_SYPHILIS2)NO" ~ "No")
  ) 


df2 %>% 
  select(year,var,vihprop,`2.5 %`,`97.5 %`) %>% 
  mutate(
    across(.cols = vihprop:`97.5 %`, .fns = ~round(.*100,1))
  ) %>% 
  DT::datatable()
```

### SIFILIS 1
```{r}
sifilis<-
  ggplot(df2, aes(x = year, y = vihprop*100, ymin = `2.5 %`*100, ymax = `97.5 %`*100, group = var)) + 
    geom_line(size = 1.2, aes(col = var))+
  geom_ribbon(aes(fill = var), alpha = 0.1)+
  #geom_errorbar(aes(color=var), width = 0.2, alpha = 0.35) +
  xlab("Years") +
    ylab("Prop. %")+
  scale_x_continuous(expand = c(0, 0), breaks = c(2010:2021), limits = c(2010,2021.1))+
  ggsci::scale_fill_futurama(alpha = 0.8)+
  ggsci::scale_color_futurama(alpha = 0.8)+

  
  theme_bw()+
  
  theme(
    axis.title = element_text(face ="bold", size = 11),
    legend.text = element_text(size = 8, face = "bold"),
    axis.text = element_text(face = "bold", family = "Arial"),
    axis.text.x = element_text( size = 9),
    legend.position = "top",
    legend.title = element_blank(),
    axis.line = element_line(colour = "black", size = 1),
    panel.background = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(face = "bold"),
    panel.grid = element_blank()
  )
```

### SIFILIS 2
```{r}
bar_sifilis<-
  ggplot(df2, aes(x = year, y = vihprop*100, group = var)) + 
  geom_col(size = 1.2, aes(fill = var))+
  ggsci::scale_fill_futurama(alpha = 0.8)+
  
  xlab("Years") +
  scale_x_continuous(expand = c(0, 0), breaks = c(2010:2021), limits = c(2009.5,2021.6))+
  ylab("Prop. %")+
  
  theme_bw()+
  
  theme(
    axis.title = element_text(face ="bold", size = 11),
    axis.title.y = element_blank(),
    legend.text = element_text(face = "bold", size = 12),
    axis.text = element_text(face = "bold"),
    legend.position = "top",
    legend.title = element_blank(),
    strip.text = element_text(face = "bold"),
    panel.grid = element_blank()
  )


```


```{r}

legend<-cowplot::get_legend(hiv)

plot_grid(plot_grid(hiv + theme(legend.position = "none"),
                    sifilis+ theme(legend.position = "none"),
                    
                    labels = c("A","B")),legend, ncol = 1, rel_heights = c(1,0.1))


ggsave("grafico1c.png", dpi = 300, width = 12, height = 5)


legend<-cowplot::get_legend(bar_hiv)

plot_grid(plot_grid(bar_hiv + theme(legend.position = "none"),
                    bar_sifilis+ theme(legend.position = "none"),
                    
                    labels = c("a","b")),legend, ncol = 1, rel_heights = c(1,0.1))


ggsave("grafico1d.png", dpi = 300, width = 12, height = 7)
```



# Grafico 2

## HIV

```{r}
df_gestantes2<-
  df_gestantes %>% 
    
  mutate(
    CHECKUP_RULE_OUT_HIV = ifelse(is.na(CHECKUP_RULE_OUT_HIV),"NO",CHECKUP_RULE_OUT_HIV)
  )
```


```{r}
df<-
  df_gestantes2 %>% 
  mutate(
    CHECKUP_RULE_OUT_HIV2 = ifelse(is.na(CHECKUP_RULE_OUT_HIV),"Missing",
                   ifelse(CHECKUP_RULE_OUT_HIV == 1,"Yes",
                          ifelse(CHECKUP_RULE_OUT_HIV == 0 | CHECKUP_RULE_OUT_HIV == 8 , "No",CHECKUP_RULE_OUT_HIV))),
    
    CHECKUP_RULE_OUT_HIV2 = as.factor(CHECKUP_RULE_OUT_HIV2)
  ) %>% 
  group_by(year) %>% 
  nest() %>% 
  mutate(
    datasvy = map(.x = data,
                  .f = ~svydesign(id =~ V001, strata =~ V022, weights=~V005, data=.x))
  )
options(survey.lonely.psu="remove")
```


```{r}
df2<-
  df %>% 
  mutate(
    vih = map(.x = datasvy,
              .f = ~svyby(~as.factor(CHECKUP_RULE_OUT_HIV), by = ~as.factor(DEPARTAMEN), design = .x, FUN =svyciprop, na.rm.all = T))
  ) %>% 
  unnest(vih) %>% 
  
  mutate(
    across(`as.factor(CHECKUP_RULE_OUT_HIV)`:`se.as.numeric(as.factor(CHECKUP_RULE_OUT_HIV))`,.fns = ~round(.,2)*100)
  ) %>%
  
  rename(
    DEPARTAMEN = `as.factor(DEPARTAMEN)`,
    `HIV Screening` = `as.factor(CHECKUP_RULE_OUT_HIV)`
  ) %>% 
  
  left_join(departamento) %>% 
  
  st_as_sf()
```


```{r}
df2 %>%
  filter(year %in% c("2010", "2021")) %>%
  ggplot(aes(fill = `HIV Screening`))+
  geom_sf(alpha = 0.8) + 
  scale_fill_carto_c(palette = "BurgYl")+
  
  guides(fill = guide_colourbar(barheight = 0.5, 
                                barwidth = 35,
                                title.position = "top",
                                direction = "horizontal"),
         
         alpha = "none")+
  facet_wrap(~year) + 
    theme(axis.title = element_blank(),
        axis.text.x = element_text(angle = 30, size = 7),
        strip.background = element_blank(),
        panel.background = element_blank(),
        strip.text = element_text(face = "bold"),
        legend.position = "bottom",
        legend.title = element_text(size = 15, face = "bold"),
        legend.key.size = unit(0.5, 'cm'))
    

ggsave("grafico5_2010_2021.png",width = 10,height = 8, dpi = 300)


```

## SIFILIS

```{r}
df_gestantes2<-
  df_gestantes %>% 
    
  mutate(
    CHECKUP_RULE_OUT_SYPHILIS = ifelse(is.na(CHECKUP_RULE_OUT_SYPHILIS),"NO",CHECKUP_RULE_OUT_SYPHILIS)
  )
```


```{r}
df<-
  df_gestantes2 %>% 
  mutate(
    CHECKUP_RULE_OUT_SYPHILIS2 = ifelse(is.na(CHECKUP_RULE_OUT_SYPHILIS),"Missing",
                   ifelse(CHECKUP_RULE_OUT_SYPHILIS == 1,"Yes",
                          ifelse(CHECKUP_RULE_OUT_SYPHILIS == 0 | CHECKUP_RULE_OUT_SYPHILIS == 8 , "No",CHECKUP_RULE_OUT_SYPHILIS))),
    
    CHECKUP_RULE_OUT_SYPHILIS2 = as.factor(CHECKUP_RULE_OUT_SYPHILIS2)
  ) %>% 
  group_by(year) %>% 
  nest() %>% 
  mutate(
    datasvy = map(.x = data,
                  .f = ~svydesign(id =~ V001, strata =~ V022, weights=~V005, data=.x))
  )
options(survey.lonely.psu="remove")
```

```{r}
df2<-
  df %>% 
  mutate(
    vih = map(.x = datasvy,
              .f = ~svyby(~as.factor(CHECKUP_RULE_OUT_SYPHILIS), by = ~as.factor(DEPARTAMEN), design = .x, FUN =svyciprop, na.rm.all = T))
  ) %>% 
  unnest(vih) %>% 
  
  mutate(
    across(`as.factor(CHECKUP_RULE_OUT_SYPHILIS)`:`se.as.numeric(as.factor(CHECKUP_RULE_OUT_SYPHILIS))`,.fns = ~round(.,2)*100)
  ) %>%
  
  rename(
    DEPARTAMEN = `as.factor(DEPARTAMEN)`,
    `Syphilis Screening` = `as.factor(CHECKUP_RULE_OUT_SYPHILIS)`
  ) %>% 
  
  left_join(departamento) %>% 
  
  st_as_sf()
```

```{r}
df2 %>%
  ggplot(aes(fill = `Syphilis Screening`))+
  geom_sf(alpha = 0.8) + 
  scale_fill_carto_c(palette = "BurgYl")+
  
  guides(fill = guide_colourbar(barheight = 0.5, 
                                barwidth = 20,
                                title.position = "top",
                                direction = "horizontal"),
         
         alpha = "none")+
  facet_wrap(~year) + 
    theme(axis.title = element_blank(),
        axis.text.x = element_text(angle = 30, size = 6),
        strip.background = element_blank(),
        panel.background = element_blank(),
        strip.text = element_text(face = "bold"),
        legend.position = "bottom",
        legend.title = element_text(size = 9, face = "bold"),
        legend.key.size = unit(0.5, 'cm'))
    

ggsave("grafico4.png",width = 13,height = 10, dpi = 300)


```

